---
# vm configs
- name: disable THP
  copy: 
    src: 'files/disable-thp.service'
    dest: '/etc/systemd/system/disable-thp.service'

- name: reload and enable 
  systemd: 
    name: disable-thp.service
    state: started
    enabled: true
    daemon_reload: true

- name: set swappiness
  sysctl:
    name: vm.swappiness
    value: '1'
    state: present
    reload: true
 
- name: configure hostname for cluster nodes
  hostname: 
    use: systemd 
    name: '{{ couchbase_data.server[count].instance.hostname }}'
  run_once: true
  delegate_to: '{{ item }}'
  loop: "{{ groups['couchbase_cluster'] }}"
  loop_control:
    index_var: count

- name: update /etc/hosts on all of the nodes
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} couchbase servers"
    block: |
      #jinja2: trim_blocks:False
      # couchbase
      {%- for count in range(server_count | int) %}
      {{ couchbase_data.server[count].instance.ip_priv1 }} {{ couchbase_data.server[count].instance.hostname }}
      {%- endfor %}  

- name: apt update
  apt:
    update_cache: true

- name: apt upgrade
  apt: 
    upgrade: true

- name: install basic packages
  apt:
    pkg:
    - net-tools
    - htop
    - rsync
    - software-properties-common
    - gnupg2
    - ssl-cert
    - python3-passlib
    - ufw

- name: secure ssh configs
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.search }}"
    line: "{{ item.replace }}"
  loop:
    - { search: '^\#?PermitRootLogin (yes|no)', replace: 'PermitRootLogin without-password' }
    - { search: '^\#?PasswordAuthentication (yes|no)', replace: 'PasswordAuthentication no' }
    - { search: '^\#?PubkeyAuthentication (yes|no)', replace: 'PubkeyAuthentication yes' }
  notify: restart ssh

- name: add couchbase ports to ufw
  include_tasks: ufw.yml

- name: create DNS records for NGINX 
  import_tasks: create_dns_records.yml
  run_once: true
  delegate_to: localhost
  when:
    - domain is defined

- name: set dns fact for default rdns
  set_fact:
    _domain: '{{ default_domain }}'
    cacheable: true
  when: domain is not defined
