---
# allowed ports include all couchbase services for dynamic scaling
# 1.2 include IP specific rules for intra-cluster
- name: allow ssh
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: copy ufw file couchbase node
  copy:
    src: 'files/couchbase_server_node'
    dest: "/etc/ufw/applications.d/couchbase-node"
    owner: root
    group: root

- name: copy ufw file couchbase pub
  copy:
    src: 'files/couchbase_server_pub'
    dest: "/etc/ufw/applications.d/couchbase-pub"
    owner: root
    group: root

- name: copy ufw file couchbase client
  copy:
    src: 'files/couchbase_server_client'
    dest: "/etc/ufw/applications.d/couchbase-client"
    owner: root
    group: root

- name: allow node to node ports
  community.general.ufw:
    rule: allow
    name: "couchbase-node"
    from: "{{ couchbase_data.server[count].instance.ip_priv1 }}"
  loop: "{{ groups['couchbase_cluster'] }}"
  loop_control:
    index_var: count

- name: allow cluster to cluster ports
  community.general.ufw:
    rule: allow
    name: "couchbase-pub"
    interface_in: eth0 
    interface_out: eth0
# should this be disabled but present for end-user?

- name: allow client ports on provisioner
  community.general.ufw:
    rule: allow
    name: "couchbase-client"
    interface_in: eth0
    interface_out: eth0
  delegate_to: "{{ groups['couchbase_cluster'][0] }}"
  run_once: true

- name: allow web ports on provisioner
  community.general.ufw:
    rule: allow
    port:
      - '80'
      - '443'
    proto: tcp
  delegate_to: "{{ groups['couchbase_cluster'][0] }}"
  run_once: true

- name: deny all others
  community.general.ufw:
    policy: deny
    direction: incoming

- name: restart ufw
  systemd: 
    name: ufw
    state: restarted
    enabled: true