---
# allowed ports include all couchbase services for dynamic scaling
# 1.2 include IP specific rules for intra-cluster
- name: allow ssh
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: move couchbase-server file for ufw
  copy:
    source: "../files/couchbase_server"
    dest: "/etc/ufw/applications.d/couchbase-server"
    owner: root
    group: root

- name: allow couchbase to couchbase ports
  community.general.ufw:
    rule: allow
    name: "couchbase-server"
    from: '{{ item }}'
    proto: tcp
  loop: '{{ couchbase_data.server[count].instance.ip_pub1 }}'
  loop_control:
    index_var: count

- name: allow web ports on provisioner
  community.general.ufw:
    rule: allow
    port:
      - '80'
      - '443'
    proto: tcp
  delegate_to: "{{ groups['couchbase_cluster'][0] }}"
  run_once: true

- name: deny all others
  community.general.ufw:
    policy: deny
    direction: incoming

- name: restart ufw
  systemd: 
    name: ufw
    state: restarted
    enabled: true