---
# copied from apps/linode_helpers/roles/certbot_ssl/tasks/certbot_standalone.yml
- name: install python3-certbot
  apt:
    name: python3-certbot
    state: present

- name: set certbot plugin
  set_fact:
    certbot_plugin: standalone
    cacheable: yes
  
# dry run
- name: run dry-run for domain
  shell:
    cmd: "certbot -n --standalone --agree-tos --dry-run certonly -d {{ _domain }} -m {{ email_address }}"
  register: dry_run
  until: dry_run is not failed
  retries: 3
  delay: 3
  ignore_errors: true

# assert that we can get valid certs. Otherwise fail - can't achieve final state
- name: validate certbot dry-run
  assert:
    that: dry_run is not failed
    fail_msg: "[Error] Certbot dry-run domain. Please check /var/log/letsencrypt/letsencrypt.log"
    success_msg: "[Info] Certbot dry-run successful!"

- name: installing let's encrypt certificate on provisioner
  shell:
    cmd: "certbot -n --standalone --agree-tos certonly -d {{ _domain }} -m {{ email_address }}"
