---
# roles/post/tasks/creds.yml

- name: writing deployment credentials locally
  blockinfile:
    path: "/home/{{ sudo_username }}/.credentials"
    create: yes
    owner: "{{ sudo_username }}"
    group: "{{ sudo_username }}"
    mode: 0644    
    block: |
      # System User 
      
      Sudo User: {{ sudo_username }}
      Password: {{ sudo_username_pass }}
      
      # Couchbase Server User

      Administrator: {{ couchbase_admin_pass }}

      # Cluster Tag 
      cluster_uuid: {{ cluster_uuid }}
    
  run_once: true
  delegate_to: "{{ groups['couchbase_cluster'][0] }}"