---
# roles/post/tasks/creds.yml

- name: writing deployment credentials locally
  blockinfile:
    path: "/home/{{ sudo_username }}/.credentials"
    create: yes
    owner: "{{ sudo_username }}"
    group: "{{ sudo_username }}"
    mode: 0644    
    block: |
      # system user 
      
      user: {{ sudo_username }}
      password: {{ sudo_username_pass }}
      
      # couchbase gui user

      Administrator: {{ couchbase_admin_pass }}

      # cluster tag 
      cluster_uuid: {{ cluster_uuid }}
    
  run_once: true
  delegate_to: "{{ groups['couchbase_cluster'][0] }}"