---
# roles/post/tasks/main.yml
- name: add nginx reverse proxy for webui
  import_tasks: nginx.yml
  delegate_to: "{{ groups['couchbase_cluster'][0] }}"
  run_once: true

- name: adding sudo user
  include_tasks: sudouser.yml

- name: dumping credentials locally
  import_tasks: creds.yml
  delegate_to: "{{ groups['couchbase_cluster'][0] }}"
  run_once: true

- name: add user ssh keys
  include_tasks: sshkeys.yml

- name: graceful exit
  meta: end_play